version: "2"
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
  api:
    build: ./api
    volumes:
      - ./api:/api
    working_dir: /api
    command: npm start
  app:
    build: ./app
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 8080:8080
